@startuml

left to right direction

actor user <<human>>
rectangle IOT <<device>> {
(interface) as i
component "wearable\ndevice" as device
(sensor) as s
}

rectangle "field gateway" {
 component gateway as field
}

rectangle "Cloud System "{
 component gateway as cloud
 component "frontend\nservice" as front
 component "backend\nservice" as back
 component "identity\nservice" as id
}

user -down-> device
device -left-> i
device -right-> s
device <- field
device -> field
field <-d-> cloud
cloud <-d-> front
front <-d-> back
front <-d-> id
back <--l--> id

@enduml
